# Generated by Django 5.2.17 on 2026-09-11 15:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'epis',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('constructeur', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('arret_requis', models.BooleanField(default=False)),
                ('mode_degrade', models.BooleanField(default=False)),
                ('impact_production', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('titre', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ordre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'etapes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Outillage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'outillages',
            },
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('constructeur', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pieces_rechange',
            },
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risques',
            },
        ),
        migrations.CreateModel(
            name='EtapeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gammes_maintenance.etape')),
            ],
            options={
                'db_table': 'etape_images',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GammeOperatoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('designation', models.CharField(max_length=500)),
                ('abreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gammes', to='gammes_maintenance.equipement')),
            ],
            options={
                'db_table': 'gammes_operatoires',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GammeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_version', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('code_version', models.CharField(max_length=20)),
                ('date_version', models.DateField(auto_now_add=True)),
                ('modifications', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('validee', 'Validée'), ('archivee', 'Archivée')], default='brouillon', max_length=20)),
                ('type_maintenance', models.CharField(blank=True, choices=[('preventif', 'Préventif'), ('correctif', 'Correctif'), ('amelioratif', 'Amélioratif')], max_length=20, null=True)),
                ('mode_maintenance', models.CharField(blank=True, choices=[('systematique', 'Systématique'), ('conditionnel', 'Conditionnel')], max_length=20, null=True)),
                ('periodicite', models.CharField(blank=True, max_length=100, null=True)),
                ('main_oeuvre', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('duree_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('referentiel', models.BooleanField(default=False)),
                ('rapport', models.BooleanField(default=False)),
                ('production', models.BooleanField(default=False)),
                ('arret', models.BooleanField(default=False)),
                ('degrade', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gammes_maintenance.gammeoperatoire')),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_redigees', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamme_versions',
                'ordering': ['-numero_version'],
            },
        ),
        migrations.CreateModel(
            name='FichierGenere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word')], max_length=20)),
                ('fichier', models.FileField(upload_to='generated/%Y/%m/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='gammes_maintenance.gammeversion')),
            ],
            options={
                'db_table': 'fichiers_generes',
            },
        ),
        migrations.AddField(
            model_name='etape',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='gammes_maintenance.gammeversion'),
        ),
        migrations.CreateModel(
            name='DocumentLie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gammes_maintenance.gammeversion')),
            ],
            options={
                'db_table': 'documents_lies',
            },
        ),
        migrations.CreateModel(
            name='QRCodeGamme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gamme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='gammes_maintenance.gammeoperatoire')),
            ],
            options={
                'db_table': 'qr_codes',
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='gammes_maintenance.gammeversion')),
            ],
            options={
                'db_table': 'recommandations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('redacteur', 'Rédacteur'), ('valideur', 'Valideur'), ('technicien', 'Technicien')], default='technicien', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VersionEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gammes_maintenance.epi')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_epis', to='gammes_maintenance.gammeversion')),
            ],
            options={
                'db_table': 'version_epis',
            },
        ),
        migrations.CreateModel(
            name='VersionOutillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('outillage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gammes_maintenance.outillage')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_outillages', to='gammes_maintenance.gammeversion')),
            ],
            options={
                'db_table': 'version_outillages',
            },
        ),
        migrations.CreateModel(
            name='VersionPieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gammes_maintenance.piecerechange')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_pieces', to='gammes_maintenance.gammeversion')),
            ],
            options={
                'db_table': 'version_pieces_rechange',
            },
        ),
        migrations.CreateModel(
            name='VersionRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gammes_maintenance.risque')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_risques', to='gammes_maintenance.gammeversion')),
            ],
            options={
                'db_table': 'version_risques',
            },
        ),
        migrations.CreateModel(
            name='ActionEtape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('contenu', models.TextField()),
                ('duree_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='gammes_maintenance.etape')),
            ],
            options={
                'db_table': 'actions_etapes',
                'ordering': ['ordre'],
                'constraints': [models.UniqueConstraint(fields=('etape', 'ordre'), name='uniq_etape_action_ordre')],
            },
        ),
        migrations.AddConstraint(
            model_name='gammeversion',
            constraint=models.UniqueConstraint(fields=('gamme', 'numero_version'), name='uniq_gamme_version'),
        ),
        migrations.AddConstraint(
            model_name='etape',
            constraint=models.UniqueConstraint(fields=('version', 'numero'), name='uniq_version_etape_numero'),
        ),
        migrations.AddConstraint(
            model_name='versionepi',
            constraint=models.UniqueConstraint(fields=('version', 'epi'), name='uniq_version_epi'),
        ),
        migrations.AddConstraint(
            model_name='versionoutillage',
            constraint=models.UniqueConstraint(fields=('version', 'outillage'), name='uniq_version_outillage'),
        ),
        migrations.AddConstraint(
            model_name='versionpiecerechange',
            constraint=models.UniqueConstraint(fields=('version', 'piece'), name='uniq_version_piece'),
        ),
        migrations.AddConstraint(
            model_name='versionrisque',
            constraint=models.UniqueConstraint(fields=('version', 'risque'), name='uniq_version_risque'),
        ),
    ]
